spring:
  # configure h2 database
  datasource:
    url: jdbc:h2:mem:db
    username: admin
    password:
  h2:
    console:
      enabled: true
      path: /h2

  # name the current microservice
  application:
    name: product-service

server:
  port: 8081

# eureka setup
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    preferIpAddress: true
